name = "superfierce-mail"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

# 自定义域名路由（注释掉可恢复仅 workers.dev 访问）
# routes = [
#   { pattern = "www.mail.imggb.top/*", zone_name = "imggb.top" }
# ]

# D1 数据库绑定
[[d1_databases]]
binding = "superfierce_mail_db"
database_name = "superfierce_mail_db"
database_id = "4dac3a67-8971-4d97-8e91-864b4a46e836"

# 环境变量


# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"

# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true



